### ISSUE TITLE
Error 500 in the error handler can't be reached.

### ISSUE THREAD

**Issue by eugenefedoto** [austinthiel/Bike-Thing#10]
https://github.com/austinthiel/Bike-Thing/blob/9c2e3cb7198ab434576fbac646ee9bf66ca67d30/app.js#L53

@austinthiel It should be changed to `res.status(err.status);`. I can't think of any way for a route to bypass the error catcher, when it will always be set to 404:

https://github.com/austinthiel/Bike-Thing/blob/9c2e3cb7198ab434576fbac646ee9bf66ca67d30/app.js#L42

**Comment by austinthiel** [comment]
Error 500 can be reached. The function setting `err.status = 404` catches nonexistent routes. The function using `res.status(err.status || 500)` us a generic error handler. So a non-404 error will go directly to the generic error handler where the status is either be predefined or set to 500.  All that code is auto-generated by Express. More info: http://expressjs.com/en/guide/error-handling.html
