### ISSUE TITLE
Change req.app.get('env') to process.env.NODE_ENV

### ISSUE THREAD

**Issue by eugenefedoto** [austinthiel/Bike-Thing#11]
https://github.com/austinthiel/Bike-Thing/blob/9c2e3cb7198ab434576fbac646ee9bf66ca67d30/app.js#L50

@austinthiel 
I believe req.app.get('env') is wrong. I did a console.log() and it returned an [object object]. It doesn't sound right that the NODE_ENV can be obtained from a request (the browser). I don't think browsers have a NODE_ENV. Maybe I'm misunderstanding something.

I tested process.env.NODE_ENV. That's giving me the correct results.

**Comment by austinthiel** [comment]
`app.get('env')` and `process.env` are interchangeable. Express generated that code and decided to use the former. https://stackoverflow.com/questions/34227216/process-env-vs-app-getenv-on-getting-the-express-js-environment
