### ISSUE TITLE
Get all networks timing out

### ISSUE THREAD

**Issue by eugenefedoto** [austinthiel/Bike-Thing#12]
https://github.com/austinthiel/Bike-Thing/blob/9c2e3cb7198ab434576fbac646ee9bf66ca67d30/routes/networks.js#L10

![Can we do something about this?](http://i.imgur.com/Kb8NNFJ.png) Is it supposed to take more than 2s?

@austinthiel @tylors1

**Comment by tylors1** [comment]
On master branch? No, it shouldnt

**Comment by eugenefedoto** [comment]
I realized my MongoDB server wasn't running.
